#ifndef _BTSTACK_CONFIG_H_
#define _BTSTACK_CONFIG_H_

// BTstack features
#define ENABLE_BLE
#define ENABLE_LE_CENTRAL
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_LE_DATA_CHANNELS
#define ENABLE_GATT_CLIENT
#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR

// Memory configuration
#define MAX_NR_HCI_CONNECTIONS 2
#define MAX_NR_GATT_CLIENTS 2
#define MAX_NR_GATT_SUBCLIENTS 4
#define MAX_NR_WHITELIST_ENTRIES 4
#define MAX_NR_SM_LOOKUP_ENTRIES 4
#define MAX_NR_SERVICE_RECORD_ITEMS 4
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 4
#define MAX_NR_LE_DEVICE_DB_ENTRIES 4

#define HCI_ACL_PAYLOAD_SIZE (255 + 4)
#define HCI_INCOMING_PRE_BUFFER_SIZE 4

#define NVM_NUM_DEVICE_DB_ENTRIES 4
#define NVM_NUM_LINK_KEYS 4

#endif /* _BTSTACK_CONFIG_H_ */
