#ifndef _BTSTACK_CONFIG_H_
#define _BTSTACK_CONFIG_H_

// BTstack features
#ifndef ENABLE_BLE
#define ENABLE_BLE
#endif
#define ENABLE_LE_CENTRAL
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_GATT_CLIENT
#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR
#define ENABLE_PRINTF_HEXDUMP

// HAL / Crypto support
#define HAVE_EMBEDDED_TIME_MS
#define HAVE_ASSERT
#define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS
#define ENABLE_SOFTWARE_AES128

// Alignment and Memory configuration
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4

#define MAX_ATT_DB_SIZE 512
#define HAVE_MALLOC

#define MAX_NR_HCI_CONNECTIONS 2
#define MAX_NR_GATT_CLIENTS 2
#define MAX_NR_GATT_SUBCLIENTS 4
#define MAX_NR_WHITELIST_ENTRIES 4
#define MAX_NR_SM_LOOKUP_ENTRIES 4
#define MAX_NR_SERVICE_RECORD_ITEMS 4
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 4
#define MAX_NR_LE_DEVICE_DB_ENTRIES 4

#define HCI_ACL_PAYLOAD_SIZE (255 + 4)
#define HCI_INCOMING_PRE_BUFFER_SIZE 8
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4

#define NVM_NUM_DEVICE_DB_ENTRIES 4
#define NVM_NUM_LINK_KEYS 4

#endif /* _BTSTACK_CONFIG_H_ */
